### ISSUE TITLE
Feat: code formatting 적용 요청

### ISSUE THREAD

**Issue by hanzsver** [seongpil0948/framework-next#26]
**Describe**
* code formatting 적용 요청드립니다.

**Comment by seongpil0948** [comment]
- https://nextjs.org/docs/pages/building-your-application/configuring/eslint
- https://medium.com/@kuwon15/nextjs-13-prettier-eslint-recoil-%EC%B4%88%EA%B8%B0-%EC%84%B8%ED%8C%85-%ED%95%98%EA%B8%B0-abc07bdbeb7f
