### ISSUE TITLE
Bug: Error boundary

### ISSUE THREAD

**Issue by seongpil0948** [seongpil0948/framework-next#71]
**Describe the bug**
401 에러가 발생해도 로그인페이지로 이동하지 않는 현상

**To Reproduce**
시크릿창 혹은 쿠키가 제거된 브라우저에서 메인페이지 접근 

**how to fix**
- https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary
- https://fe-developers.kakaoent.com/2022/221110-error-boundary/

**Comment by seongpil0948** [comment]
세진님~

**Comment by sejin-v** [comment]
네~

**Comment by seongpil0948** [comment]
https://medium.com/@matijazib/handling-errors-in-next-js-13-app-router-a-brief-guide-b3137d8d069a
